# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c8867de6e4b3b9ef48e23dedbac5bd03"
name = "Tree Master"
application_url = "https://mitchell-billy-seal-bowling.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_online_store_navigation,write_online_store_navigation,read_products,read_content"

[app_proxy]
url = "https://mitchell-billy-seal-bowling.trycloudflare.com/api"
subpath = "tree-master"
prefix = "apps"

[auth]
redirect_urls = [ "https://mitchell-billy-seal-bowling.trycloudflare.com/auth/callback" ]
